<?php

/**
 * @file
 * General functions and hook implementations.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function bouquet_plugin_filter_layout__layout_builder_alter(array &$definitions, array $extra) {
  // Remove not used layouts.
  $layouts = [
    'layout_onecol',
    'layout_twocol_section',
    'layout_threecol_section',
    'layout_fourcol_section',
    'bootstrap_layout_builder:blb_col_4',
    'bootstrap_layout_builder:blb_col_5',
    'bootstrap_layout_builder:blb_col_6',
    'bootstrap_layout_builder:blb_col_7',
    'bootstrap_layout_builder:blb_col_8',
    'bootstrap_layout_builder:blb_col_9',
    'bootstrap_layout_builder:blb_col_10',
    'bootstrap_layout_builder:blb_col_11',
    'bootstrap_layout_builder:blb_col_12',
  ];

  foreach ($layouts as $layout) {
    /** @var \Drupal\Core\Layout\LayoutDefinition[] $definitions */
    if (isset($definitions[$layout])) {
      unset($definitions[$layout]);
    }
  }

}
